"use client";

import { useCallback, useEffect, useRef } from "react";
import * as THREE from "three";
import { OrbitControls } from "three/examples/jsm/controls/OrbitControls.js";

type Rack = { id: string; name: string; code: string; rows: number; columns: number; storageType: string; width: number; depth: number; posX?: number; posZ?: number; rotation?: number };
type Cell = { id: string; rackId: string; code: string; label: string; rowIndex: number; columnIndex: number; blocked: boolean; cellWidth?: number; cellHeight?: number; cellDepth?: number };
type Stock = { productId: string; cellId: string; quantity: number; productName: string; unit: string; color?: string; packType?: string; packSize?: number };
type CameraPreset = "overview" | "front" | "left" | "right" | "top" | "zoomIn" | "zoomOut" | "rotateLeft" | "rotateRight";

function labelSprite(text: string, accent = false, scale = 1) {
  const canvas = document.createElement("canvas"); canvas.width = 640; canvas.height = 180;
  const ctx = canvas.getContext("2d")!;
  ctx.fillStyle = accent ? "rgba(255,247,237,.97)" : "rgba(255,255,255,.96)";
  ctx.strokeStyle = accent ? "#f97316" : "#cbd5e1"; ctx.lineWidth = 4; ctx.roundRect(8, 8, 624, 164, 26); ctx.fill(); ctx.stroke();
  ctx.fillStyle = "#0f172a"; ctx.font = "700 28px system-ui"; ctx.textAlign = "center"; ctx.textBaseline = "middle";
  text.split("\n").slice(0, 3).forEach((line, i) => ctx.fillText(line, 320, 48 + i * 46, 580));
  const texture = new THREE.CanvasTexture(canvas); texture.colorSpace = THREE.SRGBColorSpace;
  const sprite = new THREE.Sprite(new THREE.SpriteMaterial({ map: texture, transparent: true, depthWrite: false })); sprite.scale.set(3.4 * scale, .96 * scale, 1); return sprite;
}
function colorFromText(value?: string) {
  const map: Record<string, number> = { белый:0xf8fafc, черный:0x111827, чёрный:0x111827, красный:0xdc2626, синий:0x2563eb, зеленый:0x16a34a, зелёный:0x16a34a, желтый:0xeab308, жёлтый:0xeab308, серый:0x64748b, коричневый:0x92400e, оранжевый:0xf97316 };
  return map[(value || "").trim().toLowerCase()] || 0xd97706;
}
function packageObject(stock: Stock, scale = 1) {
  const group = new THREE.Group(); const material = new THREE.MeshStandardMaterial({ color: colorFromText(stock.color), roughness:.5, metalness:.06 }); const type=(stock.packType||"ведро").toLowerCase();
  if(type.includes("бутыл")){const b=new THREE.Mesh(new THREE.CylinderGeometry(.12*scale,.14*scale,.42*scale,20),material);b.position.y=.21*scale;const n=new THREE.Mesh(new THREE.CylinderGeometry(.055*scale,.07*scale,.13*scale,16),material);n.position.y=.485*scale;group.add(b,n);}
  else if(type.includes("канистр")){const b=new THREE.Mesh(new THREE.BoxGeometry(.35*scale,.46*scale,.25*scale),material);b.position.y=.23*scale;const n=new THREE.Mesh(new THREE.CylinderGeometry(.055*scale,.055*scale,.09*scale,16),material);n.position.set(.1*scale,.505*scale,0);group.add(b,n);}
  else if(type.includes("бан")){const b=new THREE.Mesh(new THREE.CylinderGeometry(.16*scale,.17*scale,.28*scale,24),material);b.position.y=.14*scale;group.add(b);}
  else if(type.includes("боч")){const b=new THREE.Mesh(new THREE.CylinderGeometry(.25*scale,.25*scale,.55*scale,28),material);b.position.y=.275*scale;group.add(b);}
  else {const b=new THREE.Mesh(new THREE.CylinderGeometry(.2*scale,.22*scale,.38*scale,24),material);b.position.y=.19*scale;group.add(b);}
  group.traverse(o=>{if(o instanceof THREE.Mesh){o.castShadow=true;o.receiveShadow=true;}}); return group;
}
function autoRackPosition(rack: Rack,index:number,floor:boolean){const explicit=Math.abs(Number(rack.posX||0))>.01||Math.abs(Number(rack.posZ||0))>.01;if(explicit)return{x:Number(rack.posX||0),z:Number(rack.posZ||0)};if(floor){const col=index%4,row=Math.floor(index/4);return{x:-8+col*5.2,z:7+row*4.5};}const col=index%3,row=Math.floor(index/3);return{x:-8+col*8,z:-5+row*6.5};}

export function DepartmentRoomThreeView({ racks,cells,stocks,selectedCellId,selectedRackId,onCellClick,onRackClick,onClearSelection }:{racks:Rack[];cells:Cell[];stocks:Stock[];selectedCellId?:string|null;selectedRackId?:string|null;onCellClick:(cell:Cell)=>void;onRackClick:(rack:Rack)=>void;onClearSelection:()=>void;}) {
  const hostRef=useRef<HTMLDivElement>(null); const cameraRef=useRef<THREE.PerspectiveCamera|null>(null); const controlsRef=useRef<OrbitControls|null>(null); const centerRef=useRef(new THREE.Vector3(0,2,0));
  const cameraAction=useCallback((preset:CameraPreset)=>{const camera=cameraRef.current,controls=controlsRef.current;if(!camera||!controls)return;const center=centerRef.current,offset=camera.position.clone().sub(center),distance=Math.max(7,offset.length());if(preset==="overview")camera.position.set(center.x+13,center.y+10,center.z+17);if(preset==="front")camera.position.set(center.x,center.y+4.5,center.z+Math.max(15,distance));if(preset==="left")camera.position.set(center.x-Math.max(15,distance),center.y+4.5,center.z);if(preset==="right")camera.position.set(center.x+Math.max(15,distance),center.y+4.5,center.z);if(preset==="top")camera.position.set(center.x,center.y+Math.max(18,distance),center.z+.01);if(preset==="zoomIn")camera.position.lerp(center,.18);if(preset==="zoomOut")camera.position.add(camera.position.clone().sub(center).normalize().multiplyScalar(2.8));if(preset==="rotateLeft"||preset==="rotateRight"){const angle=preset==="rotateLeft"?Math.PI/8:-Math.PI/8;const horizontal=new THREE.Vector3(camera.position.x-center.x,0,camera.position.z-center.z).applyAxisAngle(new THREE.Vector3(0,1,0),angle);camera.position.x=center.x+horizontal.x;camera.position.z=center.z+horizontal.z;}controls.target.copy(center);camera.lookAt(center);controls.update();},[]);

  useEffect(()=>{
    const host=hostRef.current;if(!host)return;host.innerHTML="";
    const scene=new THREE.Scene();scene.background=new THREE.Color(0xf1f5f9);scene.fog=new THREE.Fog(0xf1f5f9,30,70);
    const rackOnly=racks.filter(r=>r.storageType!=="floor"),floorsOnly=racks.filter(r=>r.storageType==="floor");
    const placements=[...rackOnly.map((r,i)=>autoRackPosition(r,i,false)),...floorsOnly.map((r,i)=>autoRackPosition(r,i,true))];
    const centerX=placements.length?placements.reduce((s,p)=>s+p.x,0)/placements.length:0,centerZ=placements.length?placements.reduce((s,p)=>s+p.z,0)/placements.length:0;const center=new THREE.Vector3(centerX,2.2,centerZ);centerRef.current.copy(center);
    const camera=new THREE.PerspectiveCamera(46,1,.1,140);camera.position.set(center.x+13,center.y+10,center.z+17);camera.lookAt(center);cameraRef.current=camera;
    const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(window.devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.domElement.style.width="100%";renderer.domElement.style.height="100%";renderer.domElement.style.cursor="pointer";host.appendChild(renderer.domElement);
    const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.target.copy(center);controls.maxPolarAngle=Math.PI/2.02;controls.enablePan=true;controlsRef.current=controls;
    scene.add(new THREE.HemisphereLight(0xffffff,0x64748b,2.2));const key=new THREE.DirectionalLight(0xffffff,3.2);key.position.set(center.x+10,16,center.z+10);key.castShadow=true;scene.add(key);
    const floorMesh=new THREE.Mesh(new THREE.PlaneGeometry(42,32),new THREE.MeshStandardMaterial({color:0xe5e7eb,roughness:.94}));floorMesh.rotation.x=-Math.PI/2;floorMesh.position.set(center.x,0,center.z);floorMesh.receiveShadow=true;scene.add(floorMesh);const grid=new THREE.GridHelper(42,42,0x94a3b8,0xcbd5e1);grid.position.set(center.x,.01,center.z);scene.add(grid);

    const cellInteractive:THREE.Object3D[]=[],rackInteractive:THREE.Object3D[]=[];const cellByObject=new Map<string,Cell>(),rackByObject=new Map<string,Rack>();
    const steel=new THREE.MeshStandardMaterial({color:0x334155,roughness:.42,metalness:.65}),shelf=new THREE.MeshStandardMaterial({color:0x64748b,roughness:.55,metalness:.45});
    const addBox=(group:THREE.Group,w:number,h:number,d:number,x:number,y:number,z:number,mat:THREE.Material)=>{const mesh=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat);mesh.position.set(x,y,z);mesh.castShadow=true;mesh.receiveShadow=true;group.add(mesh);return mesh;};

    rackOnly.forEach((rack,rackIndex)=>{
      const group=new THREE.Group(),pos=autoRackPosition(rack,rackIndex,false);group.position.set(pos.x,0,pos.z);group.rotation.y=Number(rack.rotation||0);scene.add(group);
      const rackCells=cells.filter(c=>c.rackId===rack.id);const rows=Array.from({length:rack.rows},(_,rr)=>rackCells.filter(c=>c.rowIndex===rr).sort((a,b)=>a.columnIndex-b.columnIndex));
      const rowHeights=rows.map(row=>Math.max(.35,...row.map(c=>Number(c.cellHeight||1.1))));const rowWidths=rows.map(row=>row.reduce((sum,c)=>sum+Math.max(.25,Number(c.cellWidth||Number(rack.width||4)/Math.max(1,rack.columns))),0));
      const rackWidth=Math.max(Number(rack.width||4),...rowWidths,1),rackDepth=Math.max(Number(rack.depth||1.2),...rackCells.map(c=>Number(c.cellDepth||rack.depth||1.2)),.8),shelfT=.09,baseT=.18,height=rowHeights.reduce((sum,h)=>sum+h+shelfT,0)+baseT;
      addBox(group,rackWidth+.4,baseT,rackDepth+.25,0,baseT/2,0,steel);
      let yCursor=baseT;
      rows.forEach((row,rr)=>{const rowH=rowHeights[rr],totalW=rowWidths[rr]||rackWidth;let xCursor=-totalW/2;row.forEach(cell=>{const cw=Math.max(.25,Number(cell.cellWidth||rackWidth/Math.max(1,row.length))),ch=Math.max(.25,Number(cell.cellHeight||rowH)),cd=Math.max(.25,Number(cell.cellDepth||rackDepth)),x=xCursor+cw/2,y=yCursor+ch/2,z=cd/2+.04;xCursor+=cw;const ss=stocks.filter(s=>s.cellId===cell.id&&Number(s.quantity)>0),occupied=ss.length>0,selected=cell.id===selectedCellId;const mat=new THREE.MeshStandardMaterial({color:selected?0xf59e0b:occupied?0xbfdbfe:0xffffff,transparent:true,opacity:selected?.92:occupied?.56:.14,emissive:selected?0xf59e0b:0x000000,emissiveIntensity:selected?.45:0});const hit=new THREE.Mesh(new THREE.BoxGeometry(Math.max(.18,cw-.05),Math.max(.18,ch-.06),.12),mat);hit.position.set(x,y,z);group.add(hit);cellInteractive.push(hit);cellByObject.set(hit.uuid,cell);addBox(group,.05,ch,Math.max(.2,cd),x-cw/2,y,0,shelf);ss.slice(0,3).forEach((stock,idx)=>{const visual=packageObject(stock,Math.min(.8,Math.max(.42,cw*.45)));visual.position.set(x+(idx-(Math.min(ss.length,3)-1)/2)*Math.min(.34,cw*.28),yCursor+.06,z+.08);group.add(visual);});const total=ss.reduce((sum,s)=>sum+Number(s.quantity),0),first=ss[0];const label=labelSprite(occupied?`${cell.code}\n${first.productName}${ss.length>1?` +${ss.length-1}`:""}\n${total.toLocaleString("ru-RU")} ${first.unit}`:`${cell.code}\n${cw.toFixed(2)}×${ch.toFixed(2)}×${cd.toFixed(2)} м`,selected||occupied,.72);label.position.set(x,y+.15,z+.34);label.scale.x=Math.min(2.7,Math.max(1.05,cw*.85));group.add(label);});if(row.length){const last=row[row.length-1],lastW=Math.max(.25,Number(last.cellWidth||1));addBox(group,.05,rowH,rackDepth,totalW/2,yCursor+rowH/2,0,shelf);}yCursor+=rowH;addBox(group,rackWidth+.15,shelfT,rackDepth,0,yCursor+shelfT/2,0,shelf);yCursor+=shelfT;});
      addBox(group,rackWidth+.4,baseT,rackDepth+.25,0,height,0,steel);for(const x of[-rackWidth/2,rackWidth/2]){addBox(group,.14,height,.14,x,height/2,-rackDepth/2,steel);addBox(group,.14,height,.14,x,height/2,rackDepth/2,steel);}const title=labelSprite(`${rack.code} · ${rack.name}`,true,.82);title.position.set(0,height+.65,0);group.add(title);
      const rackHit=new THREE.Mesh(new THREE.BoxGeometry(rackWidth+.7,height+.4,rackDepth+.7),new THREE.MeshBasicMaterial({transparent:true,opacity:0,depthWrite:false}));rackHit.position.set(0,height/2,0);group.add(rackHit);rackInteractive.push(rackHit);rackByObject.set(rackHit.uuid,rack);
      if(rack.id===selectedRackId){const helper=new THREE.BoxHelper(group,0xf97316);helper.material.depthTest=false;helper.renderOrder=30;scene.add(helper);}
    });

    floorsOnly.forEach((zone,i)=>{const pos=autoRackPosition(zone,i,true),x=pos.x,z=pos.z,w=Math.max(1.4,Number(zone.width||2)),d=Math.max(1.4,Number(zone.depth||2)),cell=cells.find(c=>c.rackId===zone.id);if(!cell)return;const ss=stocks.filter(s=>s.cellId===cell.id&&Number(s.quantity)>0),selected=zone.id===selectedRackId;const pad=new THREE.Mesh(new THREE.BoxGeometry(w,.12,d),new THREE.MeshStandardMaterial({color:selected?0xf59e0b:0xfef3c7,transparent:true,opacity:.72,roughness:.8}));pad.position.set(x,.07,z);pad.receiveShadow=true;scene.add(pad);rackInteractive.push(pad);rackByObject.set(pad.uuid,zone);const cols=Math.max(1,Math.ceil(Math.sqrt(Math.max(1,ss.length))));ss.forEach((stock,productIndex)=>{const quantity=Math.max(1,Math.min(6,Math.ceil(Number(stock.quantity)/(Number(stock.packSize)||Number(stock.quantity)||1)))),groupX=x+((productIndex%cols)-(cols-1)/2)*Math.min(1.05,w/Math.max(1,cols)),groupZ=z+Math.floor(productIndex/cols)*Math.min(1,d/Math.max(1,cols))-(Math.floor((ss.length-1)/cols)*.45);for(let b=0;b<quantity;b++){const visual=packageObject(stock,.95);visual.position.set(groupX+((b%3)-1)*.42,.12,groupZ+(Math.floor(b/3)-.5)*.42);scene.add(visual);}const label=labelSprite(`${stock.productName}\n${Number(stock.quantity).toLocaleString("ru-RU")} ${stock.unit}`,true,.58);label.position.set(groupX,1.25+productIndex*.18,groupZ);scene.add(label);});if(!ss.length){const label=labelSprite(`${zone.code} · ${zone.name}\nНапольная зона\nСвободно`,true,.72);label.position.set(x,1.3,z);scene.add(label);}if(selected){const helper=new THREE.BoxHelper(pad,0xf97316);helper.material.depthTest=false;helper.renderOrder=30;scene.add(helper);}});

    const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2();let downX=0,downY=0;const onDown=(e:PointerEvent)=>{downX=e.clientX;downY=e.clientY;};const onUp=(e:PointerEvent)=>{if(Math.hypot(e.clientX-downX,e.clientY-downY)>6)return;const r=renderer.domElement.getBoundingClientRect();pointer.x=((e.clientX-r.left)/r.width)*2-1;pointer.y=-((e.clientY-r.top)/r.height)*2+1;raycaster.setFromCamera(pointer,camera);const cellHit=raycaster.intersectObjects(cellInteractive,false)[0];if(cellHit){const cell=cellByObject.get(cellHit.object.uuid);if(cell){onCellClick(cell);return;}}const rackHit=raycaster.intersectObjects(rackInteractive,false)[0];if(rackHit){const rack=rackByObject.get(rackHit.object.uuid);if(rack){onRackClick(rack);return;}}onClearSelection();};
    renderer.domElement.addEventListener("pointerdown",onDown);renderer.domElement.addEventListener("pointerup",onUp);
    const resize=()=>{const w=Math.max(320,host.clientWidth),h=Math.max(640,host.clientHeight);camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h,false);};const observer=new ResizeObserver(resize);observer.observe(host);resize();let frame=0;const animate=()=>{controls.update();renderer.render(scene,camera);frame=requestAnimationFrame(animate);};animate();
    return()=>{cancelAnimationFrame(frame);observer.disconnect();renderer.domElement.removeEventListener("pointerdown",onDown);renderer.domElement.removeEventListener("pointerup",onUp);controls.dispose();cameraRef.current=null;controlsRef.current=null;scene.traverse(o=>{if(o instanceof THREE.Mesh){o.geometry.dispose();if(Array.isArray(o.material))o.material.forEach(m=>m.dispose());else o.material.dispose();}if(o instanceof THREE.Sprite){o.material.map?.dispose();o.material.dispose();}});renderer.dispose();host.innerHTML="";};
  },[racks,cells,stocks,selectedCellId,selectedRackId,onCellClick,onRackClick,onClearSelection]);

  const btn=(label:string,preset:CameraPreset)=><button type="button" onClick={()=>cameraAction(preset)} className="rounded-lg border bg-white/95 px-3 py-2 text-xs font-bold text-slate-700 shadow-sm hover:bg-orange-50">{label}</button>;
  return <div className="relative overflow-hidden rounded-3xl border bg-slate-100 shadow-inner"><div ref={hostRef} className="h-[76vh] min-h-[680px] w-full"/><div className="absolute left-1/2 top-3 flex max-w-[94%] -translate-x-1/2 flex-wrap justify-center gap-1.5 rounded-2xl border bg-white/90 p-2 shadow-lg backdrop-blur">{btn("Обзор","overview")}{btn("Спереди","front")}{btn("Слева","left")}{btn("Справа","right")}{btn("Сверху","top")}{btn("−","zoomOut")}{btn("+","zoomIn")}{btn("↶","rotateLeft")}{btn("↷","rotateRight")}</div><div className="pointer-events-none absolute bottom-4 left-1/2 -translate-x-1/2 rounded-full border bg-white/90 px-4 py-2 text-xs font-medium text-slate-600 shadow">Стеллаж — выбор объекта · ячейка — выбор ячейки · пустое место — снять выделение</div></div>;
}
